### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by WenXin20** [ArekkuusuJerii/OffHandCombat#1]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Offhand Combat v1.0.0.0`

I got a crash immediately after launch with Mixin.
[Crash Report](https://gist.github.com/WenXin20/64934a50a9b2da3f4d00a9249efcf45f)

**Comment by ArekkuusuJerii** [comment]
Right, do you know what other mods you were using?

**Comment by ArekkuusuJerii** [comment]
Ok so it looks like I have to add a special case when optifine is installed, no problema, will get it fixed.

**Comment by WenXin20** [comment]
Ok, thanks!
