### ISSUE TITLE
Crashed Apon Loading into a Saved World

### ISSUE THREAD

**Issue by Coraline77447** [ArekkuusuJerii/OffHandCombat#2]
Hi! I've recently discovered this mod which is like a 1.12.2 mod called Better Combat: Rebirth and apon loading into my saved world called Nina North the game crashes with this mod. Here's both the crash report and the log:

Crash report: https://pastebin.com/AgG13LKR

Log: [2020-11-06-2.log.gz](https://github.com/ArekkuusuJerii/OffHandCombat/files/5500130/2020-11-06-2.log.gz)

Edit and disclaimer: Mixin was already booted before the crash happened when trying to load onto a saved world so there's no need for Mixin Bootstrap and if I were to try to make a new world the game would've crashed still due to this issue that's within this mod.

**Comment by ArekkuusuJerii** [comment]
Oh, 1.16,4, got it

**Comment by ArekkuusuJerii** [comment]
done
