### ISSUE TITLE
White Screen Issue

### ISSUE THREAD

**Issue by Coraline77447** [ArekkuusuJerii/OffHandCombat#3]
![2020-11-09_05 25 49](https://user-images.githubusercontent.com/72243304/98543108-33b20e80-224f-11eb-96b5-676511f80ef4.png)

When I died by a group of zombies my screen instantly went like this in the screenshot above and I had to go into spectator mode and use what Gravestone mod provided me to make it back to my grave while the screen was still white but before I decided to go into spectator mode I latterly tried to go back to where I died without being able to see exept for using my minimap to see where I was going... When I gotten my stuff in spectator mode I had to go back to survival mode (since graves in creative can be destroyed and everything in the grave will be deleted) and blindly break my grave since the screen was still white and all I had for me to see was my minimap... before I went on my blinded white trip back to where I died to retrieve my items I tried to fix the issue by leaving the world and rejoining it and nothing worked so after I tpped back home using the minimap mod's tp I left the world and took out the mod to see if this mod was causing the issue and when I returned onto my world I'm able to see again but now I can't use this mod again till this issue gets fixed.... But at least I was able to dual wield my weapons before this issue happened when I died by a group of zombies in an abandoned mineshaft... I hope this comment ain't too much to read and I was trying to upload the screenshot in the comment section of this mod on curseforge but I wasn't able too...  

UPDATE; It happened again but without this mod installed.... Now Idk what's going on with my modded minecraft cause every one to two deaths my screen whites out....

FINAL UPDATE; I think that the cause of the problem was that I made my modded world when forge was at 35.0.1 that my launcher (Tlauncher) is using and I manually installed the latest version of forge that possibly bugged out the world that every time I died or every few times that I died that the screen would get whiteout... How I know this is cause I made a test world and /kill @s or /kill Coraline77447 over 20 times, 8 times without the three mods that I took out of my mods folder then I reinstalled one of the three mods that I thought was causing this problem and then /kill Coraline77447 10 times, then again after I reinstalled the third mod, after all of that while on the test world and still didn't got white screened so then I went back onto the world that I played on and after I /kill Coraline77447 3 times I gotten white screened which told me that the world got bugged by possibly updating forge manually from 35.0.1 to the latest version of forge... Which lead me to delete the world... So I would like to apologize for reporting a false report for an issue that was solved by just making a new world and making you waste your time reading this 
<:((

So you can just ignore this entire thing altogether and again I'm sorry for reporting a false report on an issue that was solved by just making a new modded survival world (even though I didn't make a new modded survival world yet) and wasting your time reading all of this................. <:((

**Comment by ArekkuusuJerii** [comment]
:0 please think nothing of it. so it stopped?
